[package]
name = "auto-palette-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Tatsuya Maki <t28oogle@gmail.com>"]
description = "A Rust library for extracting a color palette from an image automatically."
repository = "https://github.com/t28hub/auto-palette-rs"

[dependencies]
num-traits = "0.2.15"
rand = "0.8.5"
thiserror = "1.0.38"

[dev-dependencies]

[dev-dependencies.image]
version = "0.24.5"
default-features = false
features = ["jpeg", "png"]
